# $schema: https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json

Transform: AWS::Serverless-2016-10-31

Parameters:
  DynamoDBARN:
    Type: String
    Default: arn:aws:dynamodb:ap-south-1:513758042129:table/url-shortener-test

Globals:
  Function:
    Architectures:
      - arm64
    MemorySize: 1024
    Runtime: python3.12
    Timeout: 900
    CodeUri: ../


Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaDynamoDBAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "dynamodb:*"
                Resource:
                  - !Ref DynamoDBARN
                  - !Sub "${DynamoDBARN}/index/*"

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api-gateway
      StageName: dev


  Signup:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaRole.Arn
      Handler: app.lambdas.auth.signup_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Method: POST
            Path: /auth/signup

  Login:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaRole.Arn
      Handler: app.lambdas.auth.login_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Method: POST
            Path: /auth/login
